### get requst
# @name lukeRespose
GET http://localhost:8081/user/isLoggedIn HTTP/1.1




### post request
POST http://localhost:8081/customer/one HTTP/1.1
content-type: application/json

{
    "firstName": "sample1",
    "lastName": "name"
}

###
POST http://localhost:8081/user/signup HTTP/1.1
content-type: application/json

{
    "firstName": "Lil3",
    "lastName": "Daw3",
    "email":"test3@yahoo.com",
    "about":"excelent student",
    "status": "active",
    "password":"123"
}

####
POST http://localhost:8081/user/signin HTTP/1.1
content-type: application/json

{
    "email":"captain@gmail.com",
    "password":"123"
}






















### post request
GET http://localhost:8081/customer/all HTTP/1.1
### post request
GET http://localhost:8081/user/isLoggedIn HTTP/1.1




###
POST http://localhost:8081/user/signup HTTP/1.1
content-type: application/json

{
    "firstName": "Cap",
    "lastName": "Captain",
    "email":"cap@gmail.com",
    "password":"123",
    "phone": "5124546",
    "address": "123 main st",
    "role": "Captain"
}















###
GET http://localhost:8081/schedule HTTP/1.1

























###
### post request
POST http://localhost:8081/schedule/one HTTP/1.1
content-type: application/json

{
    "name": "10am Shift", 
    "start": "2020-11-09", 
    "end": "2020-11-09", 
    "color": "primary",
    "email": "test924@yahoo.com"
}

###
### get request
GET http://localhost:8081/schedule/all HTTP/1.1

###
GET http://localhost:8081/employee HTTP/1.1


###
POST http://localhost:8081/schedule/alluser HTTP/1.1
content-type: application/json

{
    "email": "man@gmail.com"
}

###
POST http://localhost:8081/schedule/del HTTP/1.1
content-type: application/json

{
    "scheduleId": 57
}
### post request
POST http://localhost:8081/schedule/one HTTP/1.1
content-type: application/json

{
  "scheduleId" : 1,
  "name": "11am Shift",
  "start": "2020-11-04",
  "end": "2020-11-04",
  "color": "primary",
  "unableToCome":false,
  "unableToCome_reason": null,
  "employee": [
    {
      "employeeId": 8,
      "firstName": "Lily",
      "lastName": "Dawit",
      "email": "bdawitdana@gmail.com",
      "Phone": "5126622281",
      "address": "5514 Griggs rd #1313",
      "employeeStatus": "Active",
      "employeeType": "Captain"
    },
    {
      "employeeId": 12,
      "firstName": "manager",
      "lastName": "man",
      "email": "man@gmail.com",
      "Phone": "5126622281",
      "address": "123 main st",
      "employeeStatus": "Active",
      "employeeType": "Manager"
    },
    {
      "employeeId": 21,
      "firstName": "Ping",
      "lastName": "chonghe",
      "email": "ping@gmail.com",
      "Phone": "511321123",
      "address": "123 main st",
      "employeeStatus": "Active",
      "employeeType": "Captain"
    }
  ]
}

### post request
POST http://localhost:8081/schedule/updateone HTTP/1.1
content-type: application/json

{
  "scheduleId" : 70,
  "name": "11am Shift",
  "start": "2020-11-04",
  "end": "2020-11-04",
  "color": "secondary",
  "employee": [
    {
      "employeeId": 8,
      "firstName": "Lily",
      "lastName": "Dawit",
      "email": "bdawitdana@gmail.com",
      "Phone": "5126622281",
      "address": "5514 Griggs rd #1313",
      "employeeStatus": "Active",
      "employeeType": "Captain"
    },
    {
      "employeeId": 12,
      "firstName": "manager",
      "lastName": "man",
      "email": "man@gmail.com",
      "Phone": "5126622281",
      "address": "123 main st",
      "employeeStatus": "Active",
      "employeeType": "Manager"
    }
  ]
}